INSERT INTO `locations hospital` (`name`, `location_city_id`)
VALUES
("Amisola Maternity Hospital", 6),
("Canossa Health and Social Center Foundation, Inc.", 6),
("Chinese General Hospital and Medical Center", 6),
("Clinica Arellano General Hospital", 6),
("De Ocampo Memorial Medical Center", 6),
("Dr. Jose Fabella Memorial Hospital", 6),
("Dr. Mirando Unciano, Sr. Medical Center", 6),
("Esperanza Health Center", 6),
("F. Lanuza Health Center and Lying", 6),
("GAT Andres Bonifacio Memorial Medical Center", 6),
("Hospital of the Infant Jesus", 6),
("Jose R. Reyes Memorial Medical Center", 6),
("Manila Doctors' Hospital", 6),
("Maria Clara Health Center and Lying", 6),
("Mary Chiles General Hospital", 6),
("Mary Johnston Hospital", 6),
("Medical Center Manila", 6),
("Metropolitan Medical Center", 6),
("Nephrology Center of Manila", 6),
("Ospital ng Maynila Medical Center", 6),
("Ospital ng Sampaloc", 6),
("Ospital ng Tondo", 6),
("Our Lady of Lourdes Hospital", 6),
("Pedro Gil Health Center and Lying", 6),
("Perpetual Help Hospital", 6),
("Perpetual Succor Hospital", 6),
("Philippine General Hospital", 6),
("Presidential Security Group Station Hospital", 6),
("Saint Jude Hospital and Medical Center", 6),
("San Lazaro Hospital", 6),
("Santa Ana Hospital", 6),
("Seamen's Hospital", 6),
("The Family Clinic, Inc.", 6),
("Tondo Foreshore Health Center", 6),
("Tondo Health Center", 6),
("Tondo Medical Center", 6),
("Trinity Woman and Child Center \"The Birthplace\"", 6),
("Unciano General Hospital", 6),
("United Doctor's Medical Center", 6),
("University of Santo Tomas Hospital", 6)