INSERT INTO `locations hospital` (`name`, `location_city_id`)
VALUES
("Ann Francis Maternity Hospital", 14),
("AFP Medical Center", 14),
("Bernardino General Hospital", 14),
("Bernardino General Hospital II", 14),
("Camp General Emilio Aguinaldo Station Hospital", 14),
("Capitol Medical Center", 14),
("Casaul General Hospital", 14),
("Commonwealth Hospital and Medical Center", 14),
("Cruz Dalida Maternity Hospital", 14),
("De Los Santos–STI Medical Center", 14),
("Dihmesco General Hospital", 14),
("Dr. Fe del Mundo Medical Center Foundation Philippines", 14),
("Dr. Carlos Lanting Hospital", 14),
("Dr. Jesus C. Delgado Memorial Medical Center", 14),
("Dr. Montano Ramos General Hospital", 14),
("East Avenue Medical Center", 14),
("Fairview General Hospital", 14),
("Far Eastern University – Nicanor Reyes Medical Foundation", 14),
("General Miguel Malvar Medical Foundation Hospital", 14),
("J. P. Sioson General Hospital and Colleges, Inc.", 14),
("Lung Center of the Philippines", 14),
("National Children's Hospital", 14),
("National Kidney and Transplant Institute", 14),
("Neopolitan General Hospital", 14),
("New Era General Hospital", 14),
("Nodado General Hospital", 14),
("Novaliches District Hospital", 14),
("Novaliches General Hospital", 14),
("OCW General Hospital", 14),
("PNP General Hospital", 14),
("PNP General Hospital Annex", 14),
("Pascual General Hospital", 14),
("Philippine Children's Medical Center", 14),
("Philippine Heart Center", 14),
("Philippine Orthopedic Center", 14),
("Quezon City General Hospital", 14),
("Queensberry Hospital", 14),
("Quezon Institute", 14),
("Quirino Memorial Medical Center", 14),
("St. Luke's Medical Center", 14),
("Saint Agnes General Hospital", 14),
("San Lorenzo General Hospital", 14),
("Santa Teresita General Hospital", 14),
("United Doctors Medical Center", 14),
("University of the East Ramon Magsaysay Memorial Medical Center", 14),
("University of the Philippines Medical Services", 14),
("Valdez Padron Hospital", 14),
("Villarosa Hospital", 14),
("Veterans Memorial Medical Center", 14),
("World Citi Medical Center", 14)