INSERT INTO `locations hospital` (`name`, `location_city_id`)
VALUES
("Acebedo General Hospital", 1),
("Baesa Advent Polyclinic and General Hospital", 1),
("Bazarte Well Family Midlife Clinic", 1),
("Col. Salvador T. Villa Memorial Hospital", 1),
("Committee of German Doctors", 1),
("Dante's Well Family Midlife Clinic", 1),
("Dr. Jose N. Rodriguez Memorial Hospital", 1),
("Fernandez General Hospital", 1),
("Francisca dela Cruz Well Family Midwife Clinic", 1),
("Jean Demegillo Maternity and Lying", 1),
("John Paul Hospital", 1),
("Lady of Lourdes Hospital of Caybiga, Inc.", 1),
("MCU–Filemon Dionisio Tanchoco Medical Foundation Hospital", 1),
("Martinez Memorial Hospital[2]", 1),
("Nephrology Center of Caloocan Dialysis Center, Inc.", 1),
("Nodado General Hospital", 1),
("North Caloocan Doctors' Hospital", 1),
("Our Lady of Grace Hospital", 1),
("President Diosdado Macapagal Memorial Medical Center", 1),
("Ronn", 1),
("San Lorenzo General Hospital", 1)