--- source http://www.mclaren.org/HealthAdvantage/AListofDefinitionsofMedicalSpecialtiesAdv.aspx ---
INSERT INTO `specializations` (`name`, `description`)
VALUES
('Allergy & Immunology','Allergic and immunologic diseases and their respiratory complications (such as pollen, chemical and food allergies, asthma and AIDS).'),
('Anesthesia','Anesthesia or relief of pain during surgery and childbirth, and control of paid due to various causes.'),
('Cardiovascular Disease','Diseases of the heart and blood vessels.'),
('Dermatology','Diseases of the skin.'),
('Emergency Medicine','Diseases that are acute medical or surgical conditions or injuries that require urgent or immediate care (usually in a hospital emergency room).'),
('Endocrinology and Metabolism','Diseases of the internal glands of the body, including diabetes mellitus.'),
('Family Practice','All diseases and related total health care of an individual and the family.'),
('Gastroenterology','Diseases of the digestive tract, including the stomach, bowel, liver and pancreas.'),
('General Practice','All diseases and related total health care of an individual and the family.'),
('Geriatric Medicine','Diseases of the elderly.'),
('Gynecology','See "Obstetrics and Gynecology".'),
('Gynecologic Oncology','Cancer diseases of the female reproductive system.'),
('Hematology','Disorders of the blood and blood-forming organs (including cancerous disorders of the blood) such as anemia, leukemia and lymphoma (see Oncology, Medical).'),
('Infectious Diseases','Infections of all types.'),
('Internal Medicine','All diseases and total health care of adults, usually 18 years of age and older.'),
('Neonatology','Disease of the newborn child.'),
('Nephrology','Diseases of the kidney, including dialysis.'),
('Neurology','Diseases of the brain, spinal cord, nervous system and related structures.'),
('Neurological Surgery','Diseases of the brain, spinal cord, nervous system and related structures requiring surgery.'),
('Obstetrics and Gynecology','Normal and abnormal pregnancy, diseases of the female reproductive system and fertility disorders.'),
('Oncology, Medical','Cancer and disorders of the blood and blood-forming organs (see Hematology).'),
('Ophthalmology','Diseases of the eye.'),
('Orthopedic Surgery','Diseases of the bones, joints, muscles and tendons.'),
('Otorhinolaryngology','Diseases of the ears, nose, sinuses, throat and upper airway passages.'),
('Pathology','Tissues and specimens removed by biopsy and surgery to diagnose normal from diseased tissues and specimens; supervises and interprets laboratory tests on blood, urine and other body fluids.'),
('Pediatrics','All diseases and total health care of newborns, infants, children and adolescents.'),
('Physical Medicine and Rehabilitation','Diseases with major and minor disabilities requiring restoration of functional ability such as assistance, retraining and recondition of muscles, tendons and extremities for ambulation and other activities of daily living.'),
('Plastic Surgery','Diseases and conditions requiring surgical reconstruction for deformity or loss of a body part, or for cosmetic purposes to improve appearance or function.'),
('Podiatric Medicine','Disease of the foot and ankle as they affect the conditions of the feet.'),
('Preventative Medicine','Health care and other measures to avoid delay or prevent disease or illness from occurring.'),
('Psychiatry','Diseases affecting mental health including diseases of the brain, nervous system and substance abuse of drugs or chemicals.'),
('Pulmonary Disease','Diseases of the lung.'),
('Radiology, Diagnostic','X-ray, ultrasound and other imaging techniques such as Computerized Tomography (CT) and Magnetic Resonance Imaging (MRI).'),
('Radiology, Nuclear','Diseases requiring use of radioactive isotopes or as an aid in diagnosis and/or therapy.'),
('Radiation Oncology','Cancer and other diseases with x-ray therapy, radioactive isotopes and linear accelerator particle radiation.'),
('Rheumatology','Diseases of the joints including arthritis and autoimmune diseases.'),
('Sports Medicine','Diseases and injuries acquired in sports.'),
('Surgery, General','Disease that require surgical operation for diagnosis or treatment.'),
('Surgery, Hand','Diseases and injuries of the nerves, tendons, muscles, bones or skin of the hand requiring surgery.'),
('Surgery, Thoracic','Diseases of the chest, including lungs, heart, blood vessels and chest wall, that require surgical operation for diagnosis and/or treatment.'),
('Surgery, Vascular','Diseases of the blood vessels that require surgical operation for diagnosis or treatment.'),
('Surgery, Colon and Rectal','Diseases of the large intestine (bowel), rectum and anus that require surgical operation for diagnosis or treatment.'),
('Surgery, Urology','Diseases of the kidneys, bladder and male reproductive tract that require surgical operation.')